server:
  port: 8120
spring:
  profiles:
    active: dev
  application:
    name: service-sms

  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 3000ms
    lettuce: # 高级客户端
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 注册中心
#    sentinel:
#      transport:
#        dashboard: localhost:8080 # sentinel控制台

aliyun:
  sms:
    regionId: ENC(gNEJ3EzUSrcjQn4b2wxevYR1pyJcJrsJ)
    keyId: ENC(QLl7ELUWFgn41TvIM+1wE/i6NHS6dev57BXGjyr3+Tc3rxn1W2RjLg==)
    keySecret: ENC(z5woNVUXG460YBvk9F7mel+bLEa/uxCcCndL0V0WnaqYpq3EBxZeww==)
    templateCode: ENC(c81B9Rmz9LDYRohxqDLTxQtTuf1iBRt5)
    signName: ENC(nZDWhnNZrT/SuQWhYKXTbvu6cChvnC3+)

# 3.x.x高版本的写法，需要带上算法，否则springboot启动失败
jasypt:
  encryptor:
    algorithm: PBEWITHMD5ANDDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

# 日志设置
logging:
  level:
    com.arui.srb.sms.client.CoreUserInfoClient: debug

feign:
  sentinel:
    enabled: true # feign开启服务熔断
#  client:
#    config:
#      default:
#        connectTimeout: 100000
#        readTimeout: 100000

